categories:
  - title: "💥 Breaking Changes"
    label: "breaking"
  - title: "🚀 Features"
    label: "enhancement"
  - title: "🔥 Removals and Deprecations"
    label: "removal"
  - title: "🐞 Fixes"
    label: "bug"
  - title: "📚 Documentation"
    label: "documentation"
  - title: "📦 Dependencies"
    label: "dependencies"
header: |
  If your inverter is not running the latest manager version, you may need to select your manager version in the integration settings. See [the wiki](https://github.com/comcowo/fsolar_modbus/wiki/Supported-Versions) for details.

  | Inverter | Supported by default | Selectable in settings |
  |---|---|---|
  | T-REX | | All |

template: |
  ## Changes

  $CHANGES
